using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core_Programming.Built_In_Functions
{
    internal class NumberGuessingGame
    {
        /*
Number Guessing Game:
Write a program where the user thinks of a number between 1 and 100, and the computer
tries to guess the number by generating random guesses.
● The user provides feedback by indicating whether the guess is high, low, or correct.
● The program should be modular, with different functions for generating guesses,
receiving user feedback, and determining the next guess
         */
        public void Game()
        {
            Console.WriteLine("Enter a number between 1 and 100:");
            int usersNumber = Convert.ToInt32(Console.ReadLine());
            Random r = new Random();
            while (true)
            {
                int randomNumber = r.Next(1, 101);
                Console.WriteLine("Random number generated by computer: " + randomNumber);
                if(randomNumber == usersNumber)
                {
                    Console.WriteLine("Guess is correct"); break;
                }
                else if(randomNumber > usersNumber)
                {
                    Console.WriteLine("Guess is higher than the user number");
                }
                else
                {
                    Console.WriteLine("Guess is smaller than the user number");
                }
            }

        }
    }
}
